### PR TITLE
Introduce new idc_update_settings_php function

### PR DESCRIPTION
**Pull request by derekbelrose**
The 99-custom-setup.sh file does not work when not using default
database connection settings such as a different password, host or database name

This introduces a new function that replicates the update_settings_php function
in utilities.sh but does not rely on rely on the DRUPAL_DFAULT_INSTALL to be true. This 
function only runs when DRUPAL_INSTANCE is not set to "dev" so it does
not affect developers..

This was tested against snapshot `upstream-20201007-739693ae-141-ga28f4f5.1611599337` and a fresh clone of `jhu-idc/idc-isle-dc`

### CODE REVIEW

**Comment by birkland** [comment]
The one major omission I see in this PR is that settings are not updated in the development environment.  Ideally, we'd have an approach to configuration that can work in all scenarios.  

I think if we were to go with this approach, we'd have to re-think how we do configuration in the development environment.  As it stands now, we commit `settings.php` to source control.  ISLE doesn't.  I think we'd need to explore doing the same (not committing settings.php) if we were to double down on this approach.  

Looking at this made me recall some experiments in configuration last year.  I created a [draft PR in idc-isle-dc](https://github.com/jhu-idc/idc-isle-dc/pull/63) and corresponding [PR in idc-isle-buildkit](https://github.com/jhu-idc/idc-isle-buildkit/pull/26) with what seemed the most transparent way of handling this problem to me at the time:  expose environment variables to php, and then use `envsubst` in the settings.php to replace `getenv(DRUPAL_ENV_VAR_NAME)` with values from the environment.  Please take a look and see what you think of that approach.

**Comment by derekbelrose** [comment]
So as it is, we're going to completely distance ourselves from the way the ISLE project does things? This creates two different ways to configure an image and creates more confusion, especially if someone needs to work with the image to move it to a new environment, such as Kubernetes.

I have concerns that the more we move away, the more this is going to become evident and problematic. Then we might was well be spinning our own images and doing things the way we want to from the start.

**Comment by derekbelrose** [comment]
it's an easy fix to get this to work in dev as well.  In fact the call in main() is wrapped in an if statement looking specifically for DRUPAL_INSTANCE = dev

```
  if [ -n "${DRUPAL_INSTANCE}" ] && [ "${DRUPAL_INSTANCE}" != "dev" ] ;
  then
      idc_update_settings_php ${site}
  fi
```

**Comment by birkland** [comment]
The tension would be due to the fact that `settings.php` is under source control, and yet can be edited upon Drupal startup.  So, for the sake of the development environment,  I think we'd either need to:
* keep default values in sync between the environment and  `settings.php`, and be aware that changes could happen that we may or may not want to commit
* .gitignore `settings.php` (this is what ISLE does)

**Review by birkland — CHANGES_REQUESTED** [review]
As it stands now, this approach is incomplete and/or problematic because the development environment does not receive any settings updates.  If we extended this approach to the development environment, it is possible that the startup process will edit `settings.php`, which is currently under source control.  

If we wanted to go this route, I believe the development environment should be treated the same with respect to config values.  This would mean re-evaluating how our settings.php is managed.

Taking a step back, I believe the approach in this PR does not align best with our needs in cases where we need to add config to `settings.php` in the future, where those config values are determined by environment variables (we'll need to do so for enabling the s3 plugin, as an example).

Using the "drush function" approach, as used in this PR, a developer would need to edit the buildkit image and create a php function known to `drush` (the current convention involves adding php code to the `drupal` buildkit image), then add the drush command to `idc_update_settings`.  An alternative, proposed in https://github.com/jhu-idc/idc-isle-buildkit/pull/26, would involve exposing environment variables to Drupal, so a developer could simply commit a `getenv()` statement in `settings.php`.  The `getenv()` approach would both suit the needs of (a) making currently un-configurable mysql settings, configurable), and (b) accommodating new config easily.

In my mind,  it is optimal to adopt a single approach, and the "expose environment variables" approach seems more straightforward and flexible to me.  Regardless, I think the fate of `settings.php` in the development environment and source control (is is `.gitignored`) would need to be decided in order to continue pursuing the approach in this PR.

**Comment by birkland** [comment]
Closed as per [decision at IDC developer meting](https://docs.google.com/document/d/149K8QsGFgyfhidOkCUodODf6hs9hjbwcR8LM25AoVic/edit#heading=h.1ek9x1tq589s)

**Pull request closed without merging**
