### PR TITLE
composer 2

### PR DESCRIPTION
**Pull request by dannylamb**
Part of https://github.com/jhu-idc/idc-isle-dc/issues/218

### CODE REVIEW

**Comment by dannylamb** [comment]
Wow, can't believe that worked out so well.  :tada: 

Switching to real PR status.

**Review by birkland — CHANGES_REQUESTED** [review]
Unfortunately, I don't think this actually installs composer 2.  

This PR has been pushed with tag `upstream-20200824-f8d1e8e-51-geffe9c4`.  If you launch idc-isle.dc with `TAG=upstream-20200824-f8d1e8e-51-geffe9c4` in the `.env` (re-building the docker-compose.yml in the process), you'll run the images this PR built.  If you hop into the Drupal container, you'll see:

```
/var/www/drupal # composer --version
Composer version 1.10.19 2020-12-04 09:14:16
```

As a sanity check, if I go into an unrelated container (e.g. solr) and execute the command for adding composer as per the new line added in this PR, it clearly adds `1.10.19-r0`
```
/opt/solr # apk add composer --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/11) Installing php7-common (7.3.30-r0)
(2/11) Installing argon2-libs (20190702-r1)
(3/11) Installing xz-libs (5.2.5-r0)
(4/11) Installing libxml2 (2.9.12-r1)
(5/11) Installing php7 (7.3.30-r0)
(6/11) Installing php7-phar (7.3.30-r0)
(7/11) Installing php7-json (7.3.30-r0)
(8/11) Installing php7-openssl (7.3.30-r0)
(9/11) Installing php7-mbstring (7.3.30-r0)
(10/11) Installing php7-iconv (7.3.30-r0)
(11/11) Installing composer (1.10.19-r0)
Executing busybox-1.31.1-r19.trigger
OK: 215 MiB in 114 packages
```

**Comment by dannylamb** [comment]
Too good to be true :disappointed:

**Comment by bseeger** [comment]
I wonder if you could have the Dockerfile run "composer self-update --2". you'll get composer 2.1.6 from that.

**Comment by dannylamb** [comment]
Yep, that appears to do it on my alpine 3.12.4 image.  Rolling that out now...

**Comment by dannylamb** [comment]
There we go... now we've got some red x's to deal with.  Progress!

**Comment by birkland** [comment]
> There we go... now we've got some red x's to deal with. Progress!

My guess:  It probably needs `ARG COMMIT` updated for each php-based microservice that's failing?

**Review by birkland — APPROVED** [review]

**Pull request merged**
