### PR TITLE
_all_ the timeouts

### PR DESCRIPTION
**Pull request by dannylamb**
This adds nginx/php timeouts to all applicable config templates.

### CODE REVIEW

**Comment by bseeger** [comment]
@birkland and @dannylamb  - I'm hopeful that we can start to move this one forward.  I think it's really affecting derivatives on the test cloud server. It's not clear why it's failing -- any clue what it's happening?

**Comment by bseeger** [comment]
Or maybe it is clear why it's failing, if this really means it's out of memory: 

`make[1]: *** [Makefile:188: set-site-uuid] Error 137`

**Comment by birkland** [comment]
@bseeger I'll take a look at it.  Re-running build to verify, but will check locally too

**Review by jhujasonw — APPROVED** [review]
I've opened an issue on the cloud app to create the new ENV vars and set them properly

Other than that, this looks good.

**Pull request merged**
